# Site settings
title: XenSibleWeb
description: Opensource XenServer and Ansible Mamagement Web Interface

username: XenSibleWeb
user_description: Opensource XenServer and Ansible Mamagement Web Interface
user_title: Opensource XenServer & Ansible Management Web Interface
email: xensibleweb@gmail.com
twitter_username: xensibleweb
github_username:  xensibleweb
gplus_username:  104775099607721156023


exclude: ['package.json', 'src' , 'node_modules']
