# Site settings
title: XenSibleWeb
description: Opensource XenServer and Ansible Mamagement Web Interface

username: XenSibleWeb
user_description: Opensource XenServer and Ansible Mamagement Web Interface
user_title: XenServer Ansible Web Interface
email: xensibleweb@gmail.com
twitter_username: xensibleweb
github_username:  xensibleweb
gplus_username:  xensibleweb


exclude: ['package.json', 'src' , 'node_modules']
